# تحديد الرامات المناسبة بدون خنق الجهاز
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تفعيل البناء المتوازي لتسريع وقت التحميل جداً
org.gradle.parallel=true

# تفعيل الكاش عشان ميبنيش الملفات مرتين ويوفر وقتك
org.gradle.caching=true

# وضع الصمت التام: إخفاء كل التحذيرات وإظهار الأخطاء القاتلة فقط
org.gradle.logging.level=quiet

android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false